version: '2.4'

services:
  core:
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: jumpserver/mysql:5
    container_name: jms_mysql
    restart: always
    command: --character-set-server=utf8
    env_file:
      - ${CONFIG_FILE}
    volumes:
      - ${CONFIG_DIR}/mysql/my.cnf:/etc/mysql/my.cnf
      - ${VOLUME_DIR}/mysql/data:/var/lib/mysql
    healthcheck:
      test: "mysql -uroot -h127.0.0.1 -p$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - net
