version: '2.4'

services:
  video:
    image: ${REGISTRY:-registry.fit2cloud.com}/jumpserver/video-worker:${VERSION}
    container_name: jms_video
    hostname: jms_video
    cpus: 2
    ulimits:
      core: 0
    restart: always
    tty: true
    env_file:
      - ${CONFIG_FILE}
    volumes:
      - ${VOLUME_DIR}/video/data:/opt/video-worker/data
    healthcheck:
      test: "curl -fsL http://localhost:9000/video-worker/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - net
