version: '2.4'

services:
  web:
    image: ${REGISTRY:-docker.io}/jumpserver/web:${VERSION}
    container_name: jms_web
    hostname: jms_web
    ulimits:
      core: 0
    restart: always
    tty: true
    environment:
      HTTP_PORT: ${HTTP_PORT:-80}
      USE_IPV6: ${USE_IPV6:-0}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-4096m}
      USE_LB: ${USE_LB:-1}
      CORE_ENABLED: ${CORE_ENABLED:-1}
      KOKO_ENABLED: ${KOKO_ENABLED:-1}
      LION_ENABLED: ${LION_ENABLED:-1}
      CHEN_ENABLED: ${CHEN_ENABLED:-1}
      KAEL_ENABLED: ${KAEL_ENABLED:-1}
    ports:
      - ${HTTP_PORT:-80}:${HTTP_PORT:-80}
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - ${VOLUME_DIR}/nginx/data/logs:/var/log/nginx
    healthcheck:
      test: "curl -k -fsL http://localhost:$$HTTP_PORT/api/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    networks:
      - net