version: '2.4'

services:
  mysql:
    image: jumpserver/mariadb:10
    container_name: jms_mysql
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      DB_PORT: $DB_PORT
      MARIADB_ROOT_PASSWORD: $DB_PASSWORD
      MARIADB_DATABASE: $DB_NAME
    volumes:
      - ${CONFIG_DIR}/mariadb/mariadb.cnf:/etc/mysql/mariadb.cnf
      - ${VOLUME_DIR}/mariadb/data:/var/lib/mysql
    healthcheck:
      test: "mysql -h127.0.0.1 -P$$DB_PORT -uroot -p$$MARIADB_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - net
